.TH "TMSMainWindow.Carrier" 3 "Fri Nov 26 2021" "Version 0.0.1" "Plakata TMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMSMainWindow.Carrier
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCarrierID\fP\fC [getset]\fP"
.br
.ti -1c
.RI "string \fBCarrierName\fP\fC [getset]\fP"
.br
.ti -1c
.RI "string \fBDepotCity\fP\fC [getset]\fP"
.br
.ti -1c
.RI "int \fBFTLA\fP\fC [getset]\fP"
.br
.ti -1c
.RI "int \fBLTLA\fP\fC [getset]\fP"
.br
.ti -1c
.RI "float \fBFTLRate\fP\fC [getset]\fP"
.br
.ti -1c
.RI "float \fBLTLRate\fP\fC [getset]\fP"
.br
.ti -1c
.RI "float \fBReefCharge\fP\fC [getset]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "int TMSMainWindow\&.Carrier\&.CarrierID\fC [get]\fP, \fC [set]\fP"

.SS "string TMSMainWindow\&.Carrier\&.CarrierName\fC [get]\fP, \fC [set]\fP"

.SS "string TMSMainWindow\&.Carrier\&.DepotCity\fC [get]\fP, \fC [set]\fP"

.SS "int TMSMainWindow\&.Carrier\&.FTLA\fC [get]\fP, \fC [set]\fP"

.SS "float TMSMainWindow\&.Carrier\&.FTLRate\fC [get]\fP, \fC [set]\fP"

.SS "int TMSMainWindow\&.Carrier\&.LTLA\fC [get]\fP, \fC [set]\fP"

.SS "float TMSMainWindow\&.Carrier\&.LTLRate\fC [get]\fP, \fC [set]\fP"

.SS "float TMSMainWindow\&.Carrier\&.ReefCharge\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Plakata TMS from the source code\&.
