.TH "TMSMainWindow.Trip" 3 "Fri Nov 26 2021" "Version 0.0.1" "Plakata TMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMSMainWindow.Trip
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBID\fP\fC [getset]\fP"
.br
.ti -1c
.RI "int \fBOrderId\fP\fC [getset]\fP"
.br
.ti -1c
.RI "int \fBTruckId\fP\fC [getset]\fP"
.br
.ti -1c
.RI "float \fBTripCost\fP\fC [getset]\fP"
.br
.ti -1c
.RI "float \fBGrossCost\fP\fC [getset]\fP"
.br
.ti -1c
.RI "float \fBKilometers\fP\fC [getset]\fP"
.br
.ti -1c
.RI "float \fBHours\fP\fC [getset]\fP"
.br
.ti -1c
.RI "int \fBOriginDepotID\fP\fC [getset]\fP"
.br
.ti -1c
.RI "string \fBOriginCity\fP\fC [getset]\fP"
.br
.ti -1c
.RI "int \fBDestinationDepotID\fP\fC [getset]\fP"
.br
.ti -1c
.RI "string \fBDestinationCity\fP\fC [getset]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "string TMSMainWindow\&.Trip\&.DestinationCity\fC [get]\fP, \fC [set]\fP"

.SS "int TMSMainWindow\&.Trip\&.DestinationDepotID\fC [get]\fP, \fC [set]\fP"

.SS "float TMSMainWindow\&.Trip\&.GrossCost\fC [get]\fP, \fC [set]\fP"

.SS "float TMSMainWindow\&.Trip\&.Hours\fC [get]\fP, \fC [set]\fP"

.SS "int TMSMainWindow\&.Trip\&.ID\fC [get]\fP, \fC [set]\fP"

.SS "float TMSMainWindow\&.Trip\&.Kilometers\fC [get]\fP, \fC [set]\fP"

.SS "int TMSMainWindow\&.Trip\&.OrderId\fC [get]\fP, \fC [set]\fP"

.SS "string TMSMainWindow\&.Trip\&.OriginCity\fC [get]\fP, \fC [set]\fP"

.SS "int TMSMainWindow\&.Trip\&.OriginDepotID\fC [get]\fP, \fC [set]\fP"

.SS "float TMSMainWindow\&.Trip\&.TripCost\fC [get]\fP, \fC [set]\fP"

.SS "int TMSMainWindow\&.Trip\&.TruckId\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Plakata TMS from the source code\&.
