.TH "TMSMainWindow.App" 3 "Fri Nov 26 2021" "Version 0.0.1" "Plakata TMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMSMainWindow.App \- Interaction logic for App\&.xaml  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Application\&.
.SH "Detailed Description"
.PP 
Interaction logic for App\&.xaml 

.SH "Author"
.PP 
Generated automatically by Doxygen for Plakata TMS from the source code\&.
