.TH "TMSMainWindow" 3 "Fri Nov 26 2021" "Version 0.0.1" "Plakata TMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMSMainWindow
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdminMainWindow\fP"
.br
.RI "Interaction logic for AdminMainWindow\&.xaml "
.ti -1c
.RI "class \fBApp\fP"
.br
.RI "Interaction logic for App\&.xaml "
.ti -1c
.RI "class \fBBuyerMainWindow\fP"
.br
.RI "Interaction logic for BuyerMainWindow\&.xaml "
.ti -1c
.RI "class \fBCarrier\fP"
.br
.ti -1c
.RI "class \fBCommTMS\fP"
.br
.ti -1c
.RI "class \fBCommunicate\fP"
.br
.RI "The purpose of this class is to allow communications between our program and a database\&. "
.ti -1c
.RI "class \fBContract\fP"
.br
.RI "The purpose of this class is to keep all the parts of a contract together\&. "
.ti -1c
.RI "class \fBOrder\fP"
.br
.RI "The purpose of this class is to keep all the parts of an order together\&. "
.ti -1c
.RI "class \fBPlannerMainWindow\fP"
.br
.RI "Interaction logic for PlannerMainWindow\&.xaml "
.ti -1c
.RI "class \fBRoleSelectWindow\fP"
.br
.RI "Interaction logic for RoleSelectWindow\&.xaml "
.ti -1c
.RI "class \fBTrip\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Plakata TMS from the source code\&.
