.TH "TMSMainWindow.PlannerMainWindow" 3 "Fri Nov 26 2021" "Version 0.0.1" "Plakata TMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMSMainWindow.PlannerMainWindow \- Interaction logic for PlannerMainWindow\&.xaml  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlannerMainWindow\fP ()"
.br
.RI "This is the function for the Planner window\&. It fills the active orders data grid with information from the TMS database\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interaction logic for PlannerMainWindow\&.xaml 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TMSMainWindow\&.PlannerMainWindow\&.PlannerMainWindow ()"

.PP
This is the function for the Planner window\&. It fills the active orders data grid with information from the TMS database\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Plakata TMS from the source code\&.
